# ============================================================
# PLACEPRO - PHASE 17 - QUESTION BANK
# ============================================================
#
# Server-side, configurable question bank for the skill assessment
# engine. 12 supported skills, ~12 questions each, covering EASY /
# MEDIUM / HARD difficulties and multiple topics per skill.
#
# SECURITY
#   - The bank lives ONLY on the server.
#   - Clients are served the question text + options but NEVER the
#     correct_answer or explanation (they are stripped by the
#     assessment service before any response is built).
#   - Scoring is always done server-side from these answers.
#
# HONESTY
#   - These are practice assessment questions, not a professionally
#     validated psychometric test. Scores reflect performance on this
#     bank only.
#
# ============================================================

from typing import Dict, List

EASY = "EASY"
MEDIUM = "MEDIUM"
HARD = "HARD"

# Difficulty point weights: harder questions are worth more, so the
# raw score reflects difficulty, not just volume.
DIFFICULTY_POINTS = {EASY: 1, MEDIUM: 2, HARD: 3}

SUPPORTED_SKILLS = [
    "Python",
    "Java",
    "C",
    "C++",
    "JavaScript",
    "SQL",
    "Data Structures",
    "Algorithms",
    "React",
    "Machine Learning",
    "HTML/CSS",
    "Git",
]

# ------------------------------------------------------------
# QUESTION BANK
# ------------------------------------------------------------
# Each question: id, skill, topic, difficulty, question_type
# ("mcq" | "integer"), question, options (mcq only), correct_answer,
# explanation. questions are kept compact but real.

QUESTION_BANK: Dict[str, List[dict]] = {
    "Python": [
        {"id": "py_001", "topic": "Variables & Types", "difficulty": EASY,
         "question_type": "mcq",
         "question": "What type does Python assign to the expression 3 + 4.5?",
         "options": ["int", "float", "str", "complex"],
         "correct_answer": "float",
         "explanation": "Adding an int to a float produces a float in Python.",
         "points": 1},
        {"id": "py_002", "topic": "Collections", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which collection is unordered and contains unique elements?",
         "options": ["list", "tuple", "dict", "set"],
         "correct_answer": "set",
         "explanation": "A set is an unordered collection of unique elements.",
         "points": 1},
        {"id": "py_003", "topic": "Functions", "difficulty": EASY,
         "question_type": "mcq",
         "question": "What is the output of: def f(a, b=2): return a + b; print(f(3))?",
         "options": ["3", "5", "6", "TypeError"],
         "correct_answer": "5",
         "explanation": "b uses its default value 2, so f(3) returns 3 + 2 = 5.",
         "points": 1},
        {"id": "py_004", "topic": "Exceptions", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which keyword is used to raise an exception manually?",
         "options": ["throw", "raise", "except", "try"],
         "correct_answer": "raise",
         "explanation": "Python uses `raise` (not `throw`) to raise exceptions.",
         "points": 2},
        {"id": "py_005", "topic": "OOP", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "What is the name of the constructor method in a Python class?",
         "options": ["__init__", "__new__", "constructor", "init"],
         "correct_answer": "__init__",
         "explanation": "__init__ is the initializer called after the instance is created.",
         "points": 2},
        {"id": "py_006", "topic": "Comprehensions", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "What does [x * 2 for x in range(3)] evaluate to?",
         "options": ["[0, 2, 4]", "[2, 4, 6]", "[0, 1, 2]", "[2, 2, 2]"],
         "correct_answer": "[0, 2, 4]",
         "explanation": "range(3) is 0,1,2; doubling each gives [0, 2, 4].",
         "points": 2},
        {"id": "py_007", "topic": "Iterators", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which of these creates a lazy sequence in Python 3?",
         "options": ["range(10)", "[1, 2, 3]", "tuple(1, 2)", "bytes(4)"],
         "correct_answer": "range(10)",
         "explanation": "range() is lazy; it does not materialize all values up front.",
         "points": 2},
        {"id": "py_008", "topic": "File Handling", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which mode opens a file for writing but does NOT truncate it?",
         "options": ["w", "a", "x", "r+"],
         "correct_answer": "a",
         "explanation": "'a' (append) writes at the end without truncating.",
         "points": 2},
        {"id": "py_009", "topic": "OOP", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What does MRO stand for in Python's multiple inheritance?",
         "options": ["Method Resolution Order", "Main Runtime Object",
                     "Module Reference Order", "Meta Return Operation"],
         "correct_answer": "Method Resolution Order",
         "explanation": "MRO is the order in which base classes are searched for methods.",
         "points": 3},
        {"id": "py_010", "topic": "Modules", "difficulty": HARD,
         "question_type": "mcq",
         "question": "Which statement makes a name importable with `from m import *`?",
         "options": ["__all__", "__init__", "__main__", "__name__"],
         "correct_answer": "__all__",
         "explanation": "`__all__` defines the names exported by `from m import *`.",
         "points": 3},
        {"id": "py_011", "topic": "Comprehensions", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What is the result of {x: x * x for x in range(3)}?",
         "options": ["{0: 0, 1: 1, 2: 4}", "[0, 1, 4]",
                     "{0, 1, 4}", "{0: 1, 1: 2, 2: 3}"],
         "correct_answer": "{0: 0, 1: 1, 2: 4}",
         "explanation": "This is a dict comprehension mapping x to x squared.",
         "points": 3},
        {"id": "py_012", "topic": "Functions", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What is a closure?",
         "options": [
             "A function that remembers variables from its enclosing scope",
             "A function defined inside a class",
             "A function that returns None",
             "A generator with a single yield"],
         "correct_answer": "A function that remembers variables from its enclosing scope",
         "explanation": "A closure captures and retains access to enclosing-scope variables.",
         "points": 3},
    ],
    "Java": [
        {"id": "java_001", "topic": "Basics", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which keyword declares a class in Java?",
         "options": ["class", "struct", "object", "type"],
         "correct_answer": "class",
         "explanation": "Java classes are declared with the `class` keyword.",
         "points": 1},
        {"id": "java_002", "topic": "Types", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which of these is a primitive type in Java?",
         "options": ["String", "Integer", "int", "Object"],
         "correct_answer": "int",
         "explanation": "int is a primitive; String/Integer/Object are reference types.",
         "points": 1},
        {"id": "java_003", "topic": "OOP", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which keyword is used to inherit a class?",
         "options": ["extends", "implements", "inherits", "super"],
         "correct_answer": "extends",
         "explanation": "`extends` inherits from a class; `implements` for interfaces.",
         "points": 1},
        {"id": "java_004", "topic": "Exceptions", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which keyword is used to declare that a method may throw an exception?",
         "options": ["throws", "throw", "try", "catch"],
         "correct_answer": "throws",
         "explanation": "`throws` declares exceptions; `throw` raises one.",
         "points": 2},
        {"id": "java_005", "topic": "Collections", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which interface represents an ordered, indexed collection?",
         "options": ["List", "Set", "Map", "Queue"],
         "correct_answer": "List",
         "explanation": "A List maintains order and allows indexed access.",
         "points": 2},
        {"id": "java_006", "topic": "OOP", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which keyword prevents a method from being overridden?",
         "options": ["final", "static", "private", "abstract"],
         "correct_answer": "final",
         "explanation": "final methods cannot be overridden.",
         "points": 2},
        {"id": "java_007", "topic": "Memory", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Where are local variables stored in Java?",
         "options": ["Stack", "Heap", "Method area", "Register"],
         "correct_answer": "Stack",
         "explanation": "Local variables live on the stack; objects on the heap.",
         "points": 2},
        {"id": "java_008", "topic": "Strings", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Why is String immutable in Java?",
         "options": [
             "For security, caching and thread safety",
             "To save memory in the heap",
             "Because strings are primitives",
             "To prevent garbage collection"],
         "correct_answer": "For security, caching and thread safety",
         "explanation": "Immutability gives caching, security and thread safety benefits.",
         "points": 2},
        {"id": "java_009", "topic": "Concurrency", "difficulty": HARD,
         "question_type": "mcq",
         "question": "Which keyword makes a block of code safe for concurrent access?",
         "options": ["synchronized", "volatile", "atomic", "locked"],
         "correct_answer": "synchronized",
         "explanation": "synchronized blocks/methods serialize access by a monitor lock.",
         "points": 3},
        {"id": "java_010", "topic": "Generics", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What is the purpose of type erasure in generics?",
         "options": [
             "Remove generic type info at runtime for backward compatibility",
             "Convert generics to arrays",
             "Speed up compilation",
             "Prevent null values"],
         "correct_answer": "Remove generic type info at runtime for backward compatibility",
         "explanation": "Erasure lets generic code run on JVMs without generic support.",
         "points": 3},
        {"id": "java_011", "topic": "JVM", "difficulty": HARD,
         "question_type": "mcq",
         "question": "Which is NOT a component of the JVM memory model?",
         "options": ["Heap", "Stack", "Program Counter", "Page cache"],
         "correct_answer": "Page cache",
         "explanation": "Heap, stack and PC registers are JVM areas; page cache is OS-level.",
         "points": 3},
        {"id": "java_012", "topic": "Streams", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What does map() do in the Java Stream API?",
         "options": [
             "Transforms each element to another value",
             "Filters elements",
             "Sorts the stream",
             "Collects to a list"],
         "correct_answer": "Transforms each element to another value",
         "explanation": "map() applies a function to each element producing a new stream.",
         "points": 3},
    ],
    "C": [
        {"id": "c_001", "topic": "Basics", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which function is the entry point of a C program?",
         "options": ["main", "start", "run", "init"],
         "correct_answer": "main",
         "explanation": "Execution begins at the main() function.",
         "points": 1},
        {"id": "c_002", "topic": "Types", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which keyword defines a constant in C?",
         "options": ["const", "static", "final", "define"],
         "correct_answer": "const",
         "explanation": "const marks a variable whose value cannot change.",
         "points": 1},
        {"id": "c_003", "topic": "Operators", "difficulty": EASY,
         "question_type": "mcq",
         "question": "What does the % operator do?",
         "options": ["Modulo (remainder)", "Percentage", "Division",
                     "Bitwise AND"],
         "correct_answer": "Modulo (remainder)",
         "explanation": "% returns the remainder of an integer division.",
         "points": 1},
        {"id": "c_004", "topic": "Pointers", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which operator dereferences a pointer?",
         "options": ["*", "&", "->", "::"],
         "correct_answer": "*",
         "explanation": "* dereferences (accesses the value pointed to); & takes an address.",
         "points": 2},
        {"id": "c_005", "topic": "Arrays", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "What is the index of the first element of a C array?",
         "options": ["0", "1", "-1", "NULL"],
         "correct_answer": "0",
         "explanation": "C arrays are zero-indexed.",
         "points": 2},
        {"id": "c_006", "topic": "Memory", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which function allocates memory on the heap?",
         "options": ["malloc", "call", "alloc", "new"],
         "correct_answer": "malloc",
         "explanation": "malloc allocates heap memory; it must be freed with free().",
         "points": 2},
        {"id": "c_007", "topic": "Strings", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "How is a string stored in C?",
         "options": [
             "As a null-terminated array of characters",
             "As a String object",
             "As a linked list of chars",
             "As a fixed-size struct"],
         "correct_answer": "As a null-terminated array of characters",
         "explanation": "C strings are char arrays terminated by the '\\0' character.",
         "points": 2},
        {"id": "c_008", "topic": "Control Flow", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "What does break do inside a loop?",
         "options": ["Exits the loop immediately", "Skips one iteration",
                     "Restarts the loop", "Ends the program"],
         "correct_answer": "Exits the loop immediately",
         "explanation": "break terminates the innermost loop or switch.",
         "points": 2},
        {"id": "c_009", "topic": "Pointers", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What is a double pointer (int **p)?",
         "options": [
             "A pointer to a pointer",
             "A pointer to two integers",
             "An array of two pointers",
             "A 64-bit pointer"],
         "correct_answer": "A pointer to a pointer",
         "explanation": "int **p points to a location holding another pointer.",
         "points": 3},
        {"id": "c_010", "topic": "Preprocessor", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What does #include do?",
         "options": [
             "Inserts the contents of a header file",
             "Links a library",
             "Defines a macro",
             "Compiles a file"],
         "correct_answer": "Inserts the contents of a header file",
         "explanation": "The preprocessor pastes the named file's contents in place.",
         "points": 3},
        {"id": "c_011", "topic": "Structures", "difficulty": HARD,
         "question_type": "mcq",
         "question": "How is a struct member accessed through a pointer?",
         "options": ["->", ".", "::", "*."],
         "correct_answer": "->",
         "explanation": "ptr->member is shorthand for (*ptr).member.",
         "points": 3},
        {"id": "c_012", "topic": "Memory", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What is a dangling pointer?",
         "options": [
             "A pointer to freed memory",
             "A NULL pointer",
             "A pointer to a stack variable",
             "An uninitialized pointer"],
         "correct_answer": "A pointer to freed memory",
         "explanation": "Dangling pointers reference memory that has been freed.",
         "points": 3},
    ],
    "C++": [
        {"id": "cpp_001", "topic": "Basics", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which operator outputs to the console in C++?",
         "options": ["<<", ">>", "cout", "printf"],
         "correct_answer": "<<",
         "explanation": "std::cout << value prints; << is the stream insertion operator.",
         "points": 1},
        {"id": "cpp_002", "topic": "OOP", "difficulty": EASY,
         "question_type": "mcq",
         "question": "What are the three access specifiers in a class?",
         "options": ["public, private, protected",
                     "public, private, internal",
                     "open, closed, static",
                     "virtual, abstract, final"],
         "correct_answer": "public, private, protected",
         "explanation": "C++ classes use public/private/protected access control.",
         "points": 1},
        {"id": "cpp_003", "topic": "Types", "difficulty": EASY,
         "question_type": "mcq",
         "question": "What is a reference in C++?",
         "options": [
             "An alias for an existing variable",
             "A pointer that cannot be NULL",
             "A constant integer",
             "A copy of a variable"],
         "correct_answer": "An alias for an existing variable",
         "explanation": "A reference is another name for an existing object.",
         "points": 1},
        {"id": "cpp_004", "topic": "Memory", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which operator allocates memory on the heap in C++?",
         "options": ["new", "malloc", "alloc", "create"],
         "correct_answer": "new",
         "explanation": "new allocates and constructs; delete deallocates.",
         "points": 2},
        {"id": "cpp_005", "topic": "OOP", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which keyword marks a method as overridable from a base class?",
         "options": ["virtual", "static", "friend", "inline"],
         "correct_answer": "virtual",
         "explanation": "virtual enables dynamic dispatch and overriding.",
         "points": 2},
        {"id": "cpp_006", "topic": "STL", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which STL container is best for fast insertion at both ends?",
         "options": ["deque", "vector", "array", "map"],
         "correct_answer": "deque",
         "explanation": "std::deque supports O(1) push/pop at both ends.",
         "points": 2},
        {"id": "cpp_007", "topic": "OOP", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "What is a pure virtual function?",
         "options": [
             "A virtual function with no body, making the class abstract",
             "A function that returns void",
             "A function that cannot be called",
             "A const member function"],
         "correct_answer": "A virtual function with no body, making the class abstract",
         "explanation": "= 0 makes a virtual function pure; the class becomes abstract.",
         "points": 2},
        {"id": "cpp_008", "topic": "RAII", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "What does RAII stand for?",
         "options": [
             "Resource Acquisition Is Initialization",
             "Random Access Index Iterator",
             "Reference And Inheritance Implementation",
             "Runtime Allocation In Iteration"],
         "correct_answer": "Resource Acquisition Is Initialization",
         "explanation": "RAII ties resource lifetime to object lifetime.",
         "points": 2},
        {"id": "cpp_009", "topic": "Move Semantics", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What does std::move() do?",
         "options": [
             "Casts a value to an rvalue reference",
             "Copies an object",
             "Deletes an object",
             "Allocates memory"],
         "correct_answer": "Casts a value to an rvalue reference",
         "explanation": "std::move enables move semantics instead of copying.",
         "points": 3},
        {"id": "cpp_010", "topic": "Templates", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What is template specialization?",
         "options": [
             "Providing a custom implementation for specific template args",
             "Instantiating a template at runtime",
             "Converting a template to a macro",
             "Removing templates from code"],
         "correct_answer": "Providing a custom implementation for specific template args",
         "explanation": "Specialization overrides the generic template for specific types.",
         "points": 3},
        {"id": "cpp_011", "topic": "Smart Pointers", "difficulty": HARD,
         "question_type": "mcq",
         "question": "Which smart pointer allows shared ownership?",
         "options": ["shared_ptr", "unique_ptr", "weak_ptr", "auto_ptr"],
         "correct_answer": "shared_ptr",
         "explanation": "shared_ptr uses reference counting for shared ownership.",
         "points": 3},
        {"id": "cpp_012", "topic": "Exceptions", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What happens if an exception is thrown and never caught?",
         "options": [
             "std::terminate is called and the program ends",
             "The program continues silently",
             "The exception is ignored",
             "A segfault occurs immediately"],
         "correct_answer": "std::terminate is called and the program ends",
         "explanation": "Uncaught exceptions call std::terminate.",
         "points": 3},
    ],
    "JavaScript": [
        {"id": "js_001", "topic": "Basics", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which keyword declares a block-scoped variable?",
         "options": ["let", "var", "define", "const_all"],
         "correct_answer": "let",
         "explanation": "let (and const) are block-scoped; var is function-scoped.",
         "points": 1},
        {"id": "js_002", "topic": "Types", "difficulty": EASY,
         "question_type": "mcq",
         "question": "What does typeof null return?",
         "options": ["object", "null", "undefined", "number"],
         "correct_answer": "object",
         "explanation": "A historical quirk: typeof null === 'object'.",
         "points": 1},
        {"id": "js_003", "topic": "Functions", "difficulty": EASY,
         "question_type": "mcq",
         "question": "What is an arrow function?",
         "options": [
             "A concise function syntax that does not bind its own this",
             "A function that runs faster",
             "A function with no arguments",
             "A method on arrays"],
         "correct_answer": "A concise function syntax that does not bind its own this",
         "explanation": "Arrow functions are concise and lexically bind `this`.",
         "points": 1},
        {"id": "js_004", "topic": "Async", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "What does a Promise represent?",
         "options": [
             "A value that may be available now, later or never",
             "A synchronous computation",
             "A callback queue",
             "A memory location"],
         "correct_answer": "A value that may be available now, later or never",
         "explanation": "Promises model eventual completion or failure of async work.",
         "points": 2},
        {"id": "js_005", "topic": "Arrays", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which method creates a NEW array with transformed elements?",
         "options": ["map", "forEach", "push", "filter"],
         "correct_answer": "map",
         "explanation": "map returns a new array; forEach returns undefined.",
         "points": 2},
        {"id": "js_006", "topic": "Objects", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "How do you convert an object to a JSON string?",
         "options": ["JSON.stringify", "JSON.parse", "toString()",
                     "Object.json()"],
         "correct_answer": "JSON.stringify",
         "explanation": "JSON.stringify serializes; JSON.parse deserializes.",
         "points": 2},
        {"id": "js_007", "topic": "Closures", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "What is a closure in JavaScript?",
         "options": [
             "A function that remembers its outer scope variables",
             "A function declared inside a class",
             "A global function",
             "An immediately invoked function"],
         "correct_answer": "A function that remembers its outer scope variables",
         "explanation": "Closures capture and keep access to their lexical scope.",
         "points": 2},
        {"id": "js_008", "topic": "DOM", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which method selects the FIRST element matching a CSS selector?",
         "options": ["querySelector", "querySelectorAll",
                     "getElementById", "getElementsByTagName"],
         "correct_answer": "querySelector",
         "explanation": "querySelector returns the first match; All returns a NodeList.",
         "points": 2},
        {"id": "js_009", "topic": "Async", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What is the event loop?",
         "options": [
             "The mechanism that processes callbacks and async tasks",
             "A loop for iterating events",
             "A DOM event handler",
             "A Promise chain"],
         "correct_answer": "The mechanism that processes callbacks and async tasks",
         "explanation": "The event loop coordinates the call stack, task and microtask queues.",
         "points": 3},
        {"id": "js_010", "topic": "Prototypes", "difficulty": HARD,
         "question_type": "mcq",
         "question": "How does inheritance work in JavaScript?",
         "options": [
             "Via the prototype chain",
             "Via class-based multiple inheritance",
             "Via interfaces",
             "Via mixin only"],
         "correct_answer": "Via the prototype chain",
         "explanation": "Objects inherit from other objects through prototypes.",
         "points": 3},
        {"id": "js_011", "topic": "ES Modules", "difficulty": HARD,
         "question_type": "mcq",
         "question": "Which syntax imports a default export?",
         "options": ["import x from 'm'", "import { x } from 'm'",
                     "require('m').x", "include 'm'"],
         "correct_answer": "import x from 'm'",
         "explanation": "Default exports use `import x from`; named use braces.",
         "points": 3},
        {"id": "js_012", "topic": "Equality", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What does 0 == '0' evaluate to in JavaScript?",
         "options": ["true", "false", "undefined", "TypeError"],
         "correct_answer": "true",
         "explanation": "== performs type coercion, so 0 == '0' is true; === is strict.",
         "points": 3},
    ],
    "SQL": [
        {"id": "sql_001", "topic": "SELECT", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which statement retrieves data from a table?",
         "options": ["SELECT", "GET", "FETCH", "READ"],
         "correct_answer": "SELECT",
         "explanation": "SELECT is the query statement for reading data.",
         "points": 1},
        {"id": "sql_002", "topic": "WHERE", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which clause filters rows before grouping?",
         "options": ["WHERE", "HAVING", "FILTER", "LIMIT"],
         "correct_answer": "WHERE",
         "explanation": "WHERE filters rows; HAVING filters groups after GROUP BY.",
         "points": 1},
        {"id": "sql_003", "topic": "Ordering", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which clause sorts the result set?",
         "options": ["ORDER BY", "SORT BY", "GROUP BY", "ARRANGE"],
         "correct_answer": "ORDER BY",
         "explanation": "ORDER BY sorts rows; GROUP BY groups them.",
         "points": 1},
        {"id": "sql_004", "topic": "JOIN", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which join returns rows with a match in EITHER table?",
         "options": ["FULL OUTER JOIN", "INNER JOIN", "LEFT JOIN",
                     "CROSS JOIN"],
         "correct_answer": "FULL OUTER JOIN",
         "explanation": "FULL OUTER JOIN keeps matched rows plus unmatched from both sides.",
         "points": 2},
        {"id": "sql_005", "topic": "Aggregation", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which function counts non-null values in a column?",
         "options": ["COUNT(column)", "SUM(column)", "TOTAL(column)",
                     "LEN(column)"],
         "correct_answer": "COUNT(column)",
         "explanation": "COUNT(column) ignores NULLs; COUNT(*) counts all rows.",
         "points": 2},
        {"id": "sql_006", "topic": "GROUP BY", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which clause filters groups created by GROUP BY?",
         "options": ["HAVING", "WHERE", "FILTER", "LIMIT"],
         "correct_answer": "HAVING",
         "explanation": "HAVING applies conditions to aggregated groups.",
         "points": 2},
        {"id": "sql_007", "topic": "Subqueries", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "What is a correlated subquery?",
         "options": [
             "A subquery that references the outer query's columns",
             "A subquery with no FROM clause",
             "A subquery using JOIN",
             "A subquery that returns multiple columns"],
         "correct_answer": "A subquery that references the outer query's columns",
         "explanation": "A correlated subquery depends on values from the outer query.",
         "points": 2},
        {"id": "sql_008", "topic": "Window Functions", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which clause defines the window for ROW_NUMBER()?",
         "options": ["OVER", "PARTITION BY only", "GROUP BY",
                     "WINDOW BY"],
         "correct_answer": "OVER",
         "explanation": "Window functions use OVER(...) to define the frame.",
         "points": 2},
        {"id": "sql_009", "topic": "Window Functions", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What does RANK() do when values tie?",
         "options": [
             "Assigns the same rank and skips subsequent ranks",
             "Assigns the same rank without skipping",
             "Assigns sequential ranks",
             "Returns the average rank"],
         "correct_answer": "Assigns the same rank and skips subsequent ranks",
         "explanation": "RANK() gaps on ties; DENSE_RANK() does not skip.",
         "points": 3},
        {"id": "sql_010", "topic": "Indexes", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What does a B-tree index do?",
         "options": [
             "Speeds up lookups and range scans on a column",
             "Stores a full copy of the table",
             "Encrypts the column",
             "Replaces the table's primary key"],
         "correct_answer": "Speeds up lookups and range scans on a column",
         "explanation": "Indexes trade write overhead for faster reads.",
         "points": 3},
        {"id": "sql_011", "topic": "Transactions", "difficulty": HARD,
         "question_type": "mcq",
         "question": "Which statement undoes a transaction's changes?",
         "options": ["ROLLBACK", "UNDO", "REVERT", "CANCEL"],
         "correct_answer": "ROLLBACK",
         "explanation": "ROLLBACK discards changes made in the current transaction.",
         "points": 3},
        {"id": "sql_012", "topic": "Joins", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What is a self join?",
         "options": [
             "Joining a table with itself",
             "Joining two copies of different tables",
             "A join with no condition",
             "A recursive query"],
         "correct_answer": "Joining a table with itself",
         "explanation": "A self join matches a table against itself using aliases.",
         "points": 3},
    ],
    "Data Structures": [
        {"id": "ds_001", "topic": "Arrays", "difficulty": EASY,
         "question_type": "mcq",
         "question": "What is the time complexity of accessing an array element by index?",
         "options": ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
         "correct_answer": "O(1)",
         "explanation": "Arrays give constant-time random access by index.",
         "points": 1},
        {"id": "ds_002", "topic": "Linked Lists", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which structure stores elements in nodes with pointers?",
         "options": ["Linked list", "Array", "Hash table", "Heap"],
         "correct_answer": "Linked list",
         "explanation": "Linked lists chain nodes via pointers.",
         "points": 1},
        {"id": "ds_003", "topic": "Stacks", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which principle does a stack follow?",
         "options": ["LIFO", "FIFO", "Priority", "Round-robin"],
         "correct_answer": "LIFO",
         "explanation": "Stacks are Last-In-First-Out; queues are FIFO.",
         "points": 1},
        {"id": "ds_004", "topic": "Queues", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which principle does a queue follow?",
         "options": ["FIFO", "LIFO", "Random", "Sorted"],
         "correct_answer": "FIFO",
         "explanation": "Queues are First-In-First-Out.",
         "points": 1},
        {"id": "ds_005", "topic": "Hash Tables", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "What is the average-case lookup complexity of a hash table?",
         "options": ["O(1)", "O(log n)", "O(n)", "O(n^2)"],
         "correct_answer": "O(1)",
         "explanation": "Good hash functions give average O(1) lookups.",
         "points": 2},
        {"id": "ds_006", "topic": "Trees", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "In a binary search tree, values on the left are...",
         "options": ["Smaller than the node", "Larger than the node",
                     "Equal to the node", "Unordered"],
         "correct_answer": "Smaller than the node",
         "explanation": "BST invariant: left subtree < node < right subtree.",
         "points": 2},
        {"id": "ds_007", "topic": "Graphs", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which traversal visits all neighbors of a node before moving deeper?",
         "options": ["BFS", "DFS", "In-order", "Post-order"],
         "correct_answer": "BFS",
         "explanation": "BFS explores level by level; DFS goes depth-first.",
         "points": 2},
        {"id": "ds_008", "topic": "Heaps", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "In a min-heap, where is the smallest element?",
         "options": ["At the root", "At a leaf", "Anywhere",
                     "In the middle"],
         "correct_answer": "At the root",
         "explanation": "A min-heap keeps the minimum at the root.",
         "points": 2},
        {"id": "ds_009", "topic": "Complexity", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What is the worst-case lookup complexity of an unbalanced BST?",
         "options": ["O(n)", "O(log n)", "O(1)", "O(n log n)"],
         "correct_answer": "O(n)",
         "explanation": "An unbalanced BST degrades to a linked list: O(n).",
         "points": 3},
        {"id": "ds_010", "topic": "Trees", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What does the height of a tree represent?",
         "options": [
             "The number of edges on the longest path from root to a leaf",
             "The number of leaves",
             "The number of nodes",
             "The depth of the shallowest leaf"],
         "correct_answer": "The number of edges on the longest path from root to a leaf",
         "explanation": "Height = longest root-to-leaf path length in edges.",
         "points": 3},
        {"id": "ds_011", "topic": "Graphs", "difficulty": HARD,
         "question_type": "mcq",
         "question": "Which algorithm finds the shortest path from one source in a weighted graph?",
         "options": ["Dijkstra", "BFS", "DFS", "Kruskal"],
         "correct_answer": "Dijkstra",
         "explanation": "Dijkstra finds shortest paths for non-negative weights.",
         "points": 3},
        {"id": "ds_012", "topic": "Tries", "difficulty": HARD,
         "question_type": "mcq",
         "question": "Which structure is ideal for prefix-based string lookups?",
         "options": ["Trie", "Stack", "Hash set", "Heap"],
         "correct_answer": "Trie",
         "explanation": "Tries support efficient prefix search over strings.",
         "points": 3},
    ],
    "Algorithms": [
        {"id": "alg_001", "topic": "Complexity", "difficulty": EASY,
         "question_type": "mcq",
         "question": "What is the time complexity of binary search on a sorted array?",
         "options": ["O(log n)", "O(n)", "O(n log n)", "O(1)"],
         "correct_answer": "O(log n)",
         "explanation": "Binary search halves the search space each step.",
         "points": 1},
        {"id": "alg_002", "topic": "Sorting", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which is the simplest O(n^2) comparison sort?",
         "options": ["Bubble sort", "Merge sort", "Quick sort",
                     "Heap sort"],
         "correct_answer": "Bubble sort",
         "explanation": "Bubble sort repeatedly swaps adjacent out-of-order elements.",
         "points": 1},
        {"id": "alg_003", "topic": "Searching", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which search requires the array to be sorted?",
         "options": ["Binary search", "Linear search", "Hash search",
                     "Interpolation-free search"],
         "correct_answer": "Binary search",
         "explanation": "Binary search relies on sorted order.",
         "points": 1},
        {"id": "alg_004", "topic": "Sorting", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "What is the worst-case complexity of quick sort?",
         "options": ["O(n^2)", "O(n log n)", "O(n)", "O(log n)"],
         "correct_answer": "O(n^2)",
         "explanation": "Poor pivot choices give O(n^2); average is O(n log n).",
         "points": 2},
        {"id": "alg_005", "topic": "Divide & Conquer", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which sort uses the divide-and-conquer strategy with merging?",
         "options": ["Merge sort", "Bubble sort", "Selection sort",
                     "Insertion sort"],
         "correct_answer": "Merge sort",
         "explanation": "Merge sort divides, sorts and merges halves.",
         "points": 2},
        {"id": "alg_006", "topic": "Greedy", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which algorithm is greedy?",
         "options": ["Dijkstra", "Merge sort", "Binary search",
                     "DFS on a tree"],
         "correct_answer": "Dijkstra",
         "explanation": "Dijkstra greedily picks the closest unvisited node.",
         "points": 2},
        {"id": "alg_007", "topic": "Dynamic Programming", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which property makes a problem solvable with dynamic programming?",
         "options": [
             "Overlapping subproblems + optimal substructure",
             "Only optimal substructure",
             "Only overlapping subproblems",
             "The absence of recursion"],
         "correct_answer": "Overlapping subproblems + optimal substructure",
         "explanation": "DP needs both overlapping subproblems and optimal substructure.",
         "points": 2},
        {"id": "alg_008", "topic": "Backtracking", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which technique tries choices and undoes them on failure?",
         "options": ["Backtracking", "Memoization", "Binary search",
                     "Counting sort"],
         "correct_answer": "Backtracking",
         "explanation": "Backtracking explores and reverts partial solutions.",
         "points": 2},
        {"id": "alg_009", "topic": "Dynamic Programming", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What does memoization do?",
         "options": [
             "Caches results of subproblems to avoid recomputation",
             "Removes recursion",
             "Sorts subproblems",
             "Reduces memory to O(1)"],
         "correct_answer": "Caches results of subproblems to avoid recomputation",
         "explanation": "Memoization stores computed subproblem answers.",
         "points": 3},
        {"id": "alg_010", "topic": "Graphs", "difficulty": HARD,
         "question_type": "mcq",
         "question": "Which algorithm finds a Minimum Spanning Tree?",
         "options": ["Kruskal", "Dijkstra", "Floyd-Warshall",
                     "Topological sort"],
         "correct_answer": "Kruskal",
         "explanation": "Kruskal (and Prim) find an MST.",
         "points": 3},
        {"id": "alg_011", "topic": "Complexity", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What is the complexity of merge sort in ALL cases?",
         "options": ["O(n log n)", "O(n^2)", "O(n)", "O(log n)"],
         "correct_answer": "O(n log n)",
         "explanation": "Merge sort is consistently O(n log n).",
         "points": 3},
        {"id": "alg_012", "topic": "Two Pointers", "difficulty": HARD,
         "question_type": "mcq",
         "question": "The two-pointer technique is most useful on which input?",
         "options": [
             "A sorted array",
             "An unsorted linked list",
             "A hash table",
             "A binary tree"],
         "correct_answer": "A sorted array",
         "explanation": "Two pointers exploit sorted order to reach O(n).",
         "points": 3},
    ],
    "React": [
        {"id": "react_001", "topic": "Components", "difficulty": EASY,
         "question_type": "mcq",
         "question": "What is a React component?",
         "options": [
             "A reusable function or class that returns UI",
             "A CSS file",
             "An HTML page",
             "A browser API"],
         "correct_answer": "A reusable function or class that returns UI",
         "explanation": "Components are the building blocks of a React UI.",
         "points": 1},
        {"id": "react_002", "topic": "JSX", "difficulty": EASY,
         "question_type": "mcq",
         "question": "What is JSX?",
         "options": [
             "A syntax extension that mixes HTML-like markup with JavaScript",
             "A JavaScript framework",
             "A CSS preprocessor",
             "A testing library"],
         "correct_answer": "A syntax extension that mixes HTML-like markup with JavaScript",
         "explanation": "JSX compiles to React.createElement calls.",
         "points": 1},
        {"id": "react_003", "topic": "Props", "difficulty": EASY,
         "question_type": "mcq",
         "question": "How do you pass data from a parent to a child component?",
         "options": ["Props", "State", "Refs", "Events"],
         "correct_answer": "Props",
         "explanation": "Props flow down from parent to child.",
         "points": 1},
        {"id": "react_004", "topic": "State", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which hook manages local state in a function component?",
         "options": ["useState", "useEffect", "useMemo", "useRef"],
         "correct_answer": "useState",
         "explanation": "useState returns a value and its setter.",
         "points": 2},
        {"id": "react_005", "topic": "Effects", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which hook runs side effects after render?",
         "options": ["useEffect", "useState", "useContext", "useReducer"],
         "correct_answer": "useEffect",
         "explanation": "useEffect handles side effects like data fetching.",
         "points": 2},
        {"id": "react_006", "topic": "Rendering", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Why is `key` required in a list of elements?",
         "options": [
             "To help React identify which items changed",
             "To style the items",
             "To sort the list",
             "To bind events"],
         "correct_answer": "To help React identify which items changed",
         "explanation": "Keys let React reconcile list items efficiently.",
         "points": 2},
        {"id": "react_007", "topic": "Virtual DOM", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "What is the virtual DOM?",
         "options": [
             "An in-memory representation of the UI used to batch updates",
             "A copy of the browser DOM stored in a database",
             "A server-side rendering cache",
             "A debugging tool"],
         "correct_answer": "An in-memory representation of the UI used to batch updates",
         "explanation": "React diffs the virtual DOM to minimize real DOM changes.",
         "points": 2},
        {"id": "react_008", "topic": "Context", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which hook reads a Context value?",
         "options": ["useContext", "useState", "useRef", "useEffect"],
         "correct_answer": "useContext",
         "explanation": "useContext subscribes a component to a Context.",
         "points": 2},
        {"id": "react_009", "topic": "Memoization", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What does useMemo do?",
         "options": [
             "Caches a computed value until dependencies change",
             "Caches a function reference",
             "Prevents re-renders entirely",
             "Stores DOM nodes"],
         "correct_answer": "Caches a computed value until dependencies change",
         "explanation": "useMemo memoizes expensive computations.",
         "points": 3},
        {"id": "react_010", "topic": "Rendering", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What is a controlled component?",
         "options": [
             "An input whose value is driven by React state",
             "A component without props",
             "A class component only",
             "A component that cannot re-render"],
         "correct_answer": "An input whose value is driven by React state",
         "explanation": "Controlled inputs read their value from state and update it via handlers.",
         "points": 3},
        {"id": "react_011", "topic": "Hooks", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What is a custom hook?",
         "options": [
             "A function starting with `use` that wraps other hooks",
             "A component that renders nothing",
             "A React plugin",
             "A reducer function"],
         "correct_answer": "A function starting with `use` that wraps other hooks",
         "explanation": "Custom hooks reuse stateful logic across components.",
         "points": 3},
        {"id": "react_012", "topic": "Performance", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What does React.memo do?",
         "options": [
             "Skips re-rendering a component when props are unchanged",
             "Caches API responses",
             "Memoizes CSS",
             "Removes unused imports"],
         "correct_answer": "Skips re-rendering a component when props are unchanged",
         "explanation": "React.memo shallow-compares props to skip renders.",
         "points": 3},
    ],
    "Machine Learning": [
        {"id": "ml_001", "topic": "Supervised Learning", "difficulty": EASY,
         "question_type": "mcq",
         "question": "What is supervised learning?",
         "options": [
             "Training on labeled data to predict labels",
             "Training without labels",
             "Reinforcement from rewards",
             "Rule-based programming"],
         "correct_answer": "Training on labeled data to predict labels",
         "explanation": "Supervised learning uses input-output pairs.",
         "points": 1},
        {"id": "ml_002", "topic": "Regression", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which task predicts a continuous value?",
         "options": ["Regression", "Classification", "Clustering",
                     "Association"],
         "correct_answer": "Regression",
         "explanation": "Regression outputs continuous values; classification outputs classes.",
         "points": 1},
        {"id": "ml_003", "topic": "Classification", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which metric is used for a binary classification model?",
         "options": ["Accuracy", "Mean squared error", "R-squared",
                     "Perplexity"],
         "correct_answer": "Accuracy",
         "explanation": "Accuracy (and precision/recall) suit classification.",
         "points": 1},
        {"id": "ml_004", "topic": "Overfitting", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "What is overfitting?",
         "options": [
             "The model memorizes training data and generalizes poorly",
             "The model is too simple",
             "The model trains too slowly",
             "The model has no parameters"],
         "correct_answer": "The model memorizes training data and generalizes poorly",
         "explanation": "Overfitting means high train but low test performance.",
         "points": 2},
        {"id": "ml_005", "topic": "Evaluation", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Why is a train/test split needed?",
         "options": [
             "To estimate performance on unseen data",
             "To speed up training",
             "To reduce memory usage",
             "To label the data"],
         "correct_answer": "To estimate performance on unseen data",
         "explanation": "Held-out data gives an unbiased performance estimate.",
         "points": 2},
        {"id": "ml_006", "topic": "Feature Engineering", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "What is feature scaling?",
         "options": [
             "Transforming features to a comparable range",
             "Deleting features",
             "Combining models",
             "Augmenting images"],
         "correct_answer": "Transforming features to a comparable range",
         "explanation": "Scaling (e.g. standardization) helps distance-based models.",
         "points": 2},
        {"id": "ml_007", "topic": "Models", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which model is an ensemble of decision trees?",
         "options": ["Random Forest", "Linear Regression", "K-Means",
                     "Naive Bayes"],
         "correct_answer": "Random Forest",
         "explanation": "Random forests average many trees.",
         "points": 2},
        {"id": "ml_008", "topic": "Unsupervised Learning", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which algorithm performs clustering?",
         "options": ["K-Means", "Linear Regression", "Logistic Regression",
                     "Decision Tree"],
         "correct_answer": "K-Means",
         "explanation": "K-Means partitions data into k clusters.",
         "points": 2},
        {"id": "ml_009", "topic": "Deep Learning", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What is backpropagation?",
         "options": [
             "Computing gradients by propagating error backward",
             "Forwarding data through layers",
             "A regularization method",
             "A data augmentation trick"],
         "correct_answer": "Computing gradients by propagating error backward",
         "explanation": "Backpropagation computes gradients for weight updates.",
         "points": 3},
        {"id": "ml_010", "topic": "Evaluation", "difficulty": HARD,
         "question_type": "mcq",
         "question": "When is accuracy misleading?",
         "options": [
             "With imbalanced classes",
             "With numeric features",
             "With large datasets",
             "With decision trees"],
         "correct_answer": "With imbalanced classes",
         "explanation": "On skewed classes a model can be accurate yet useless.",
         "points": 3},
        {"id": "ml_011", "topic": "Regularization", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What does L2 regularization do?",
         "options": [
             "Penalizes large weights to reduce overfitting",
             "Drops random neurons",
             "Adds more features",
             "Increases learning rate"],
         "correct_answer": "Penalizes large weights to reduce overfitting",
         "explanation": "L2 adds a squared-weight penalty term.",
         "points": 3},
        {"id": "ml_012", "topic": "NLP", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What does TF-IDF measure?",
         "options": [
             "How important a word is to a document in a corpus",
             "Word frequency in speech",
             "Sentence length",
             "Vocabulary size"],
         "correct_answer": "How important a word is to a document in a corpus",
         "explanation": "TF-IDF weighs term frequency against corpus rarity.",
         "points": 3},
    ],
    "HTML/CSS": [
        {"id": "web_001", "topic": "HTML", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which tag defines the largest heading?",
         "options": ["<h1>", "<h6>", "<heading>", "<head>"],
         "correct_answer": "<h1>",
         "explanation": "<h1> is the top-level heading tag.",
         "points": 1},
        {"id": "web_002", "topic": "HTML", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which attribute specifies the destination of a link?",
         "options": ["href", "src", "alt", "rel"],
         "correct_answer": "href",
         "explanation": "Anchors use href for the link target.",
         "points": 1},
        {"id": "web_003", "topic": "CSS", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which property changes the text color?",
         "options": ["color", "font-color", "text-color", "background"],
         "correct_answer": "color",
         "explanation": "CSS `color` sets the text color.",
         "points": 1},
        {"id": "web_004", "topic": "CSS", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which value of position fixes an element relative to the viewport?",
         "options": ["fixed", "static", "relative", "absolute"],
         "correct_answer": "fixed",
         "explanation": "position: fixed anchors to the viewport.",
         "points": 2},
        {"id": "web_005", "topic": "CSS Box Model", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which CSS property controls space INSIDE an element's border?",
         "options": ["padding", "margin", "border", "spacing"],
         "correct_answer": "padding",
         "explanation": "padding is inside the border; margin is outside.",
         "points": 2},
        {"id": "web_006", "topic": "Flexbox", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which property aligns items along the main axis in flexbox?",
         "options": ["justify-content", "align-items", "flex-wrap",
                     "align-self"],
         "correct_answer": "justify-content",
         "explanation": "justify-content controls main-axis alignment.",
         "points": 2},
        {"id": "web_007", "topic": "Responsive", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "What does a media query do?",
         "options": [
             "Applies styles conditionally based on viewport/device",
             "Loads images lazily",
             "Caches stylesheets",
             "Compresses CSS"],
         "correct_answer": "Applies styles conditionally based on viewport/device",
         "explanation": "Media queries enable responsive design.",
         "points": 2},
        {"id": "web_008", "topic": "CSS Specificity", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which selector has the highest specificity?",
         "options": ["#id", ".class", "element", "*"],
         "correct_answer": "#id",
         "explanation": "IDs beat classes, elements and universal selectors.",
         "points": 2},
        {"id": "web_009", "topic": "CSS Grid", "difficulty": HARD,
         "question_type": "mcq",
         "question": "Which property defines columns in CSS Grid?",
         "options": ["grid-template-columns", "grid-columns",
                     "display: grid-columns", "columns"],
         "correct_answer": "grid-template-columns",
         "explanation": "grid-template-columns defines the track list.",
         "points": 3},
        {"id": "web_010", "topic": "Accessibility", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What does the alt attribute provide?",
         "options": [
             "Alternative text for screen readers and broken images",
             "A link target",
             "A style class",
             "A caption"],
         "correct_answer": "Alternative text for screen readers and broken images",
         "explanation": "alt text is essential for accessibility.",
         "points": 3},
        {"id": "web_011", "topic": "Performance", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What does the loading=\"lazy\" attribute do?",
         "options": [
             "Defers loading off-screen images",
             "Preloads all images",
             "Removes images",
             "Encodes images"],
         "correct_answer": "Defers loading off-screen images",
         "explanation": "Lazy loading improves initial page performance.",
         "points": 3},
        {"id": "web_012", "topic": "Cascade", "difficulty": HARD,
         "question_type": "mcq",
         "question": "Which rule overrides conflicting CSS declarations?",
         "options": [
             "The one with highest specificity / later position",
             "The shortest rule",
             "The first rule",
             "The one written in uppercase"],
         "correct_answer": "The one with highest specificity / later position",
         "explanation": "The cascade resolves conflicts by specificity then order.",
         "points": 3},
    ],
    "Git": [
        {"id": "git_001", "topic": "Basics", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which command stages changes?",
         "options": ["git add", "git commit", "git push", "git clone"],
         "correct_answer": "git add",
         "explanation": "git add moves changes to the staging area.",
         "points": 1},
        {"id": "git_002", "topic": "Basics", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which command records staged changes to the repository?",
         "options": ["git commit", "git add", "git status", "git diff"],
         "correct_answer": "git commit",
         "explanation": "git commit creates a snapshot of staged changes.",
         "points": 1},
        {"id": "git_003", "topic": "Remotes", "difficulty": EASY,
         "question_type": "mcq",
         "question": "Which command uploads local commits to a remote?",
         "options": ["git push", "git pull", "git fetch", "git merge"],
         "correct_answer": "git push",
         "explanation": "git push transfers local commits to the remote.",
         "points": 1},
        {"id": "git_004", "topic": "Branches", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which command creates a new branch?",
         "options": ["git branch new-name", "git new branch",
                     "git checkout --branch-new", "git fork new-name"],
         "correct_answer": "git branch new-name",
         "explanation": "git branch <name> creates (git switch -c checks out).",
         "points": 2},
        {"id": "git_005", "topic": "History", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which command shows the commit history?",
         "options": ["git log", "git history", "git show --all",
                     "git status"],
         "correct_answer": "git log",
         "explanation": "git log lists commits in reverse chronological order.",
         "points": 2},
        {"id": "git_006", "topic": "Merging", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "What is a merge conflict?",
         "options": [
             "Conflicting changes to the same lines from different branches",
             "A network error during push",
             "An uncommitted file",
             "A missing remote"],
         "correct_answer": "Conflicting changes to the same lines from different branches",
         "explanation": "Git cannot auto-merge overlapping edits and asks the user.",
         "points": 2},
        {"id": "git_007", "topic": "Undo", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "Which command discards uncommitted local changes to a file?",
         "options": ["git checkout -- file", "git rm file",
                     "git reset --soft file", "git clean file"],
         "correct_answer": "git checkout -- file",
         "explanation": "checkout -- restores the file from the index/HEAD.",
         "points": 2},
        {"id": "git_008", "topic": "Stashing", "difficulty": MEDIUM,
         "question_type": "mcq",
         "question": "What does git stash do?",
         "options": [
             "Temporarily saves uncommitted changes",
             "Deletes commits",
             "Squashes commits",
             "Uploads to a remote"],
         "correct_answer": "Temporarily saves uncommitted changes",
         "explanation": "stash shelves work-in-progress for later (stash pop).",
         "points": 2},
        {"id": "git_009", "topic": "Rebasing", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What does git rebase do?",
         "options": [
             "Reapplies commits onto a new base",
             "Deletes old commits",
             "Merges two remotes",
             "Rewrites file contents"],
         "correct_answer": "Reapplies commits onto a new base",
         "explanation": "Rebase moves a branch's commits onto another base.",
         "points": 3},
        {"id": "git_010", "topic": "Git Internals", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What is HEAD in Git?",
         "options": [
             "A pointer to the current commit/branch",
             "The latest remote commit",
             "The first commit",
             "A tag"],
         "correct_answer": "A pointer to the current commit/branch",
         "explanation": "HEAD references your current position in history.",
         "points": 3},
        {"id": "git_011", "topic": "Collaboration", "difficulty": HARD,
         "question_type": "mcq",
         "question": "What does a pull request enable?",
         "options": [
             "Proposed changes to be reviewed before merging",
             "Automatic deployment",
             "Repository deletion",
             "Direct code execution"],
         "correct_answer": "Proposed changes to be reviewed before merging",
         "explanation": "PRs formalize review before integration.",
         "points": 3},
        {"id": "git_012", "topic": "History", "difficulty": HARD,
         "question_type": "mcq",
         "question": "Which command rewrites the last commit message?",
         "options": ["git commit --amend", "git commit --fix",
                     "git log --edit", "git rebase --message"],
         "correct_answer": "git commit --amend",
         "explanation": "--amend replaces the most recent commit.",
         "points": 3},
    ],
}


def get_questions(skill: str) -> List[dict]:
    """Return the question list for a canonical skill (or []).

    Each question is stamped with its `skill` (the bank itself does
    not repeat the key on every entry).
    """
    questions = QUESTION_BANK.get(skill, [])
    return [{**q, "skill": skill} for q in questions]


def get_skill_topics(skill: str) -> List[str]:
    """Distinct topics covered for a skill, in bank order."""
    topics = []
    for q in QUESTION_BANK.get(skill, []):
        if q["topic"] not in topics:
            topics.append(q["topic"])
    return topics


def question_count() -> int:
    """Total number of questions in the bank."""
    return sum(len(qs) for qs in QUESTION_BANK.values())


def skills_in_bank() -> List[str]:
    """Skills that have at least one question."""
    return [s for s in SUPPORTED_SKILLS if QUESTION_BANK.get(s)]
