import IconMark from "../components/IconMark";

const scoreData = [
  { label: "Academic Performance", value: 82, detail: "CGPA 8.2 / 10" },
  { label: "Technical Skills", value: 76, detail: "Based on coursework & projects" },
  { label: "Aptitude", value: 80, detail: "Aptitude score 80 / 100" },
  { label: "Communication", value: 75, detail: "Communication skill 75 / 100" },
  { label: "Logical Reasoning", value: 78, detail: "Logical reasoning 78 / 100" },
  { label: "Coding Skill", value: 75, detail: "Coding skill 75 / 100" },
  { label: "Attendance", value: 88, detail: "Attendance 88%" },
];

const activityData = [
  { label: "Internships", value: 2, note: "2 internships completed" },
  { label: "Projects", value: 3, note: "3 academic / personal projects" },
  { label: "Certifications", value: 4, note: "4 certifications earned" },
  { label: "Hackathons", value: 2, note: "2 hackathons participated" },
  { label: "Backlogs", value: 0, note: "No active backlogs" },
];

const strengths = [
  "Strong academic performance",
  "Good aptitude",
  "Good logical reasoning",
  "Good communication",
  "Internship experience",
  "Good attendance",
];

const improvements = [
  "Improve coding skills",
  "Complete more internships",
  "Increase GitHub contributions",
  "Learn trending technologies",
  "Improve mock interview performance",
];

const getRating = (value) => {
  if (value >= 85) return { label: "Excellent", className: "rating-excellent" };
  if (value >= 70) return { label: "Good", className: "rating-good" };
  if (value >= 50) return { label: "Average", className: "rating-average" };
  return { label: "Needs Work", className: "rating-low" };
};

function ScoreCard({ label, value, detail }) {
  const rating = getRating(value);

  return (
    <div className="score-card">
      <div className="score-card-header">
        <span className="score-label">{label}</span>
        <span className="score-value">
          {value}
          <small>/100</small>
        </span>
      </div>

      <div className="progress-track">
        <div
          className={`progress-fill ${rating.className}`}
          style={{ width: `${value}%` }}
        ></div>
      </div>

      <div className="score-card-footer">
        <span className="score-detail">{detail}</span>
        <span className={`rating-badge ${rating.className}`}>{rating.label}</span>
      </div>
    </div>
  );
}

function PerformanceAnalysis() {
  const overall = Math.round(
    scoreData.reduce((sum, item) => sum + item.value, 0) / scoreData.length
  );

  return (
    <div className="analysis-page">
      <div className="page-header">
        <h1>Performance Analysis</h1>
        <p>
          A breakdown of the student's placement-related performance across
          academic, technical, and soft-skill areas.
        </p>
      </div>

      <div className="analysis-summary">
        <div className="analysis-overall">
          <span className="analysis-overall-label">Overall Readiness Score</span>
          <span className="analysis-overall-value">
            {overall}
            <small>/100</small>
          </span>
          <span className="analysis-overall-note">
            Weighted average of all performance areas
          </span>
        </div>

        <div className="analysis-summary-note">
          <strong>Sample data notice:</strong> All scores shown on this page are
          sample/demo values for illustration. They are <em>not</em> generated by
          the ML model and will be replaced once the backend API is integrated.
        </div>
      </div>

      <div className="analysis-section">
        <h2>
          <IconMark name="performance" className="section-title-icon" />
          <span>Score Breakdown</span>
        </h2>

        <div className="score-grid">
          {scoreData.map((item) => (
            <ScoreCard key={item.label} {...item} />
          ))}
        </div>
      </div>

      <div className="analysis-section">
        <h2>
          <IconMark name="experience" className="section-title-icon" />
          <span>Experience & Activities</span>
        </h2>

        <div className="activity-grid">
          {activityData.map((item) => (
            <div key={item.label} className="activity-card">
              <span className="activity-value">{item.value}</span>
              <span className="activity-label">{item.label}</span>
              <span className="activity-note">{item.note}</span>
            </div>
          ))}
        </div>
      </div>

      <div className="analysis-split">
        <div className="analysis-card strengths-card">
          <h2>
            <IconMark name="strengths" className="section-title-icon" />
            <span>Strengths</span>
          </h2>

          <ul>
            {strengths.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </div>

        <div className="analysis-card improvements-card">
          <h2>
            <IconMark name="improve" className="section-title-icon" />
            <span>Areas for Improvement</span>
          </h2>

          <ul>
            {improvements.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
}

export default PerformanceAnalysis;
