import { useState } from "react";
import IconMark from "../components/IconMark";
import EditProfileModal from "../components/EditProfileModal";

const PROFILE_KEY = "placepro_profile";

const defaultProfile = {
  name: "Bhargav",
  branch: "Information Science and Engineering",
  collegeTier: "Tier 2",
  cgpa: "8.2",
  attendance: "88",
  internships: "2",
  projects: "3",
  certifications: "4",
  githubRepositories: "5",
  linkedinConnections: "120",
};

function loadProfile() {
  try {
    const raw = localStorage.getItem(PROFILE_KEY);
    if (raw) {
      return { ...defaultProfile, ...JSON.parse(raw) };
    }
  } catch {
    // Ignore malformed storage and fall back to defaults.
  }
  return defaultProfile;
}

function StudentProfile({
  editOpen = false,
  onRequestEdit,
  onCloseEdit,
}) {
  const [profile, setProfile] = useState(loadProfile);

  const handleSave = (data) => {
    setProfile(data);
    try {
      localStorage.setItem(PROFILE_KEY, JSON.stringify(data));
      window.dispatchEvent(new Event("placepro-profile-updated"));
    } catch {
      // Storage may be unavailable; profile still updates in memory.
    }
    if (onCloseEdit) {
      onCloseEdit();
    }
  };

  const academicData = [
    { label: "CGPA", value: profile.cgpa, detail: "out of 10" },
    {
      label: "College Tier",
      value: profile.collegeTier,
      detail: "Institution category",
    },
    {
      label: "Attendance",
      value: `${profile.attendance}%`,
      detail: "Overall attendance",
    },
    { label: "Backlogs", value: "0", detail: "Active backlogs" },
  ];

  const experienceData = [
    {
      label: "Internships",
      value: profile.internships,
      detail: "Completed internships",
    },
    {
      label: "Projects",
      value: profile.projects,
      detail: "Academic & personal projects",
    },
    {
      label: "Certifications",
      value: profile.certifications,
      detail: "Earned certifications",
    },
    { label: "Hackathons", value: "2", detail: "Hackathons participated" },
    {
      label: "GitHub Repositories",
      value: profile.githubRepositories,
      detail: "Public repositories",
    },
    {
      label: "LinkedIn Connections",
      value: profile.linkedinConnections,
      detail: "Professional network",
    },
    { label: "Volunteer Experience", value: "Yes", detail: "Volunteering activity" },
  ];

  const skillData = [
    { label: "Coding Skill", value: 75 },
    { label: "Aptitude Score", value: 80 },
    { label: "Communication", value: 75 },
    { label: "Logical Reasoning", value: 78 },
    { label: "Mock Interview", value: 70 },
    { label: "Leadership", value: 75 },
  ];

  return (
    <div className="profile-page">
      <div className="page-header">
        <h1>Student Profile</h1>
        <p>View student academic and professional information.</p>
      </div>

      <div className="profile-card">
        <div className="profile-card-top">
          <div className="profile-intro">
            <div className="profile-avatar gradient">
              {profile.name ? profile.name.charAt(0).toUpperCase() : "?"}
            </div>

            <div className="profile-identity">
              <h2>{profile.name}</h2>
              <p>{profile.branch}</p>
              <div className="profile-badges">
                <span className="profile-badge">Student</span>
                <span className="profile-badge">
                  {profile.collegeTier} College
                </span>
              </div>
            </div>
          </div>

          <button
            type="button"
            className="dash-btn secondary profile-edit-btn"
            onClick={onRequestEdit}
          >
            Edit Profile
          </button>
        </div>

        <p className="profile-data-note">
          <strong>Sample data notice:</strong> The information on this page is
          sample/demo data for illustration. It is not generated by the ML model
          and will be replaced once the backend API is integrated.
        </p>
      </div>

      <div className="profile-section">
        <h2>
          <IconMark name="academic" className="section-title-icon" />
          <span>Academic Information</span>
        </h2>

        <div className="profile-grid">
          {academicData.map((item) => (
            <div key={item.label} className="profile-item">
              <span>{item.label}</span>
              <strong>{item.value}</strong>
              <small>{item.detail}</small>
            </div>
          ))}
        </div>
      </div>

      <div className="profile-section">
        <h2>
          <IconMark name="experience" className="section-title-icon" />
          <span>Experience & Activities</span>
        </h2>

        <div className="profile-grid">
          {experienceData.map((item) => (
            <div key={item.label} className="profile-item">
              <span>{item.label}</span>
              <strong>{item.value}</strong>
              <small>{item.detail}</small>
            </div>
          ))}
        </div>
      </div>

      <div className="profile-section">
        <h2>
          <IconMark name="skills" className="section-title-icon" />
          <span>Skills & Assessments</span>
        </h2>

        <div className="profile-grid">
          {skillData.map((item) => (
            <div key={item.label} className="profile-item">
              <span>{item.label}</span>
              <strong>
                {item.value}
                <small> / 100</small>
              </strong>
              <div className="profile-bar">
                <div
                  className="profile-bar-fill"
                  style={{ width: `${item.value}%` }}
                ></div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {editOpen && (
        <EditProfileModal
          profile={profile}
          onSave={handleSave}
          onClose={onCloseEdit}
        />
      )}
    </div>
  );
}

export default StudentProfile;
